# %% [markdown]
# # Phase 0 — data audit
#
# Loads every file, checks the data traps listed in PLAN.md §2, and writes
# counts per position / draft class / drill to `reports/00_audit.md`.
# Every `check(...)` is a hard assertion: if the data changes under us, this fails.
#
# Run: `python notebooks/00_audit.py` (opens as a notebook via jupytext percent format).

# %%
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import pandas as pd  # noqa: E402

from src.data import PARQUET, connect, to_parquet  # noqa: E402

to_parquet()
con = connect()
report: list[str] = ["# Phase 0 — data audit", "", "Generated by `notebooks/00_audit.py`. Do not edit by hand.", ""]
checks: list[str] = []


def df(sql: str) -> pd.DataFrame:
    return con.sql(sql).df()


def one(sql: str):
    return con.sql(sql).fetchone()[0]


def check(name: str, ok: bool, detail: str = "") -> None:
    checks.append(f"- [{'x' if ok else ' '}] {name}" + (f" — {detail}" if detail else ""))
    assert ok, f"{name}: {detail}"


def md_table(d: pd.DataFrame) -> str:
    def fmt(v):
        if pd.isna(v):
            return ""
        if isinstance(v, float):
            return f"{v:,.0f}" if v == int(v) else f"{v:,.2f}"
        if isinstance(v, int):
            return f"{v:,}"
        return str(v)

    cols = [str(c) for c in d.columns]
    rows = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    rows += ["| " + " | ".join(fmt(v) for v in r) + " |" for r in d.itertuples(index=False)]
    return "\n".join(rows)


def section(title: str, d: pd.DataFrame | None = None, note: str = "") -> None:
    report.extend([f"## {title}", ""])
    if note:
        report.extend([note, ""])
    if d is not None:
        report.extend([md_table(d), ""])
    print(f"\n== {title}\n{'' if d is None else d.to_string(index=False)}")


# %% [markdown]
# ## 1. Files load; keys are unique; every ID belongs to the 510-player cohort

# %%
counts = df(
    "SELECT * FROM ("
    + " UNION ALL ".join(
        f"SELECT '{p.stem}' AS file, count(*) AS rows FROM '{p}'" for p in sorted(PARQUET.glob("*.parquet"))
    )
    + ")"
)
section("Row counts", counts)

n_players = one("SELECT count(DISTINCT nfl_id) FROM players")
check("players.csv has 510 unique players", n_players == 510 == one("SELECT count(*) FROM players"))
for t in ["combine_results", "player_career_successes"]:
    check(f"{t}: one row per player, all in players.csv",
          one(f"SELECT count(DISTINCT nfl_id) FROM {t} WHERE nfl_id IN (SELECT nfl_id FROM players)")
          == one(f"SELECT count(*) FROM {t}") == 510)
check("combine_tracking: every player ID is in players.csv",
      one("SELECT count(*) FROM combine_tracking WHERE entity_type='PLAYER' AND nfl_id NOT IN (SELECT nfl_id FROM players)") == 0)
check("game tracking: every nfl_id is a cohort rookie (no teammates/opponents)",
      one("SELECT count(DISTINCT nfl_id) FROM game_tracking WHERE nfl_id NOT IN (SELECT nfl_id FROM players)") == 0)
check("player_play: every nfl_id is a cohort rookie",
      one("SELECT count(*) FROM player_play WHERE nfl_id NOT IN (SELECT nfl_id FROM players)") == 0)
check("player_play: unique on (game_id, play_id, nfl_id)",
      one("SELECT count(*) FROM (SELECT 1 FROM player_play GROUP BY game_id, play_id, nfl_id HAVING count(*) > 1)") == 0)

# %% [markdown]
# ## 2. Cohort: position x draft class

# %%
section(
    "Players by draft class",
    df("""SELECT draft_year, count(*) AS players, count(draft_overall_pick) AS drafted,
                 count(*) - count(draft_overall_pick) AS udfa
          FROM players GROUP BY 1 ORDER BY 1"""),
    "UDFA = null `draft_overall_pick`.",
)
section(
    "Players by NFL position and draft class",
    df("""SELECT p.nfl_position, c.combine_position, count(*) AS total,
                 count(*) FILTER (WHERE p.draft_year = 2023) AS "2023",
                 count(*) FILTER (WHERE p.draft_year = 2024) AS "2024",
                 count(*) FILTER (WHERE p.draft_year = 2025) AS "2025"
          FROM players p JOIN combine_results c USING (nfl_id)
          GROUP BY ALL ORDER BY total DESC, 1"""),
    "No QBs, effectively no RBs, and no off-ball linebackers in the cohort.",
)

# %% [markdown]
# ## 3. Standard combine testing coverage (the baseline model's inputs)

# %%
tests = ["ten_yd_split", "forty", "vertical", "broad_jump", "three_cone", "short_shuttle", "bench_reps",
         "ngs_athleticism_score"]
section(
    "Standard combine results: % of players with a value, by combine position",
    df("SELECT combine_position, count(*) AS n, "
       + ", ".join(f"round(100 * avg(({c} IS NOT NULL)::int)) AS {c}" for c in tests)
       + " FROM combine_results GROUP BY 1 ORDER BY n DESC"),
    "3-cone and shuttle are missing for most players, so a baseline needs imputation or must drop them.",
)

# %% [markdown]
# ## 4. Combine tracking: drills, reps, sampling

# %%
section(
    "Combine tracking by drill type",
    df("""SELECT drill_type, count(DISTINCT nfl_id) AS players, count(DISTINCT event_id) AS reps,
                 count(DISTINCT drill_name) AS drill_names, count(*) AS frames
          FROM combine_tracking WHERE entity_type = 'PLAYER' GROUP BY 1 ORDER BY 1"""),
    "One rep = one `event_id`. A few reps share `(nfl_id, drill_name, attempt)`, so key reps on `event_id`.",
)
section(
    "Players with tracking, by combine position x drill type",
    df("""PIVOT (SELECT c.combine_position, t.drill_type, t.nfl_id
                 FROM combine_tracking t JOIN combine_results c USING (nfl_id)
                 WHERE t.entity_type = 'PLAYER')
          ON drill_type USING count(DISTINCT nfl_id) GROUP BY combine_position ORDER BY combine_position"""),
)
section(
    "WR position drills (SKILL_DRILLS_WR)",
    df("""SELECT drill_name, count(DISTINCT nfl_id) AS players, count(DISTINCT event_id) AS reps,
                 round(count(*) / count(DISTINCT event_id), 1) AS avg_frames
          FROM combine_tracking WHERE drill_type = 'SKILL_DRILLS_WR' AND entity_type = 'PLAYER'
          GROUP BY 1 ORDER BY players DESC"""),
)
check("combine_tracking: one player per event",
      one("SELECT max(n) FROM (SELECT count(DISTINCT nfl_id) n FROM combine_tracking WHERE entity_type='PLAYER' GROUP BY event_id)") == 1)
dt = df("""SELECT DISTINCT round(epoch_ms(time) - lag(epoch_ms(time)) OVER (PARTITION BY event_id, entity_type ORDER BY time)) AS dt
           FROM combine_tracking QUALIFY dt IS NOT NULL""")
check("combine_tracking: strictly 10 Hz, no gaps", dt["dt"].tolist() == [100.0], f"frame gaps (ms): {dt['dt'].tolist()}")

# %% [markdown]
# ## 5. Game tracking: season types and the REG-season filter

# %%
section(
    "games.csv",
    df("""SELECT season, season_type, count(*) AS games, min(week) AS wk_min, max(week) AS wk_max
          FROM games GROUP BY ALL ORDER BY 1, 2"""),
)
section(
    "Game tracking by season and season type (all files)",
    df("""SELECT season, season_type, count(DISTINCT game_id) AS games,
                 count(DISTINCT (game_id, play_id, nfl_id)) AS player_plays, count(*) AS frames,
                 round(100 * count(*) / sum(count(*)) OVER (PARTITION BY season), 1) AS pct_frames
          FROM game_tracking GROUP BY season, season_type ORDER BY 1, 2"""),
    "Preseason and playoff frames must be excluded; use the `game_tracking_reg` view.",
)
files = ", ".join(f"'{PARQUET}/game_tracking_{y}.parquet'" for y in (2023, 2024, 2025))
raw_frames = one(f"SELECT count(*) FROM read_parquet([{files}])")
check("game tracking: every game_id is in games.csv (no orphan frames)",
      raw_frames == one("SELECT count(*) FROM game_tracking"), f"{raw_frames:,} frames")
for y in (2023, 2024, 2025):
    check(f"game_tracking_{y}.csv holds season {y} only",
          one(f"SELECT count(*) FROM '{PARQUET}/game_tracking_{y}.parquet' t JOIN games g USING (game_id) WHERE g.season <> {y}") == 0)
check("game tracking: no duplicate frames",
      one(f"SELECT count(*) FROM (SELECT 1 FROM read_parquet([{files}]) GROUP BY game_id, play_id, nfl_id, time HAVING count(*) > 1)") == 0)
check("REG filter: game_tracking_reg has no PRE/POST frames",
      one("SELECT count(*) FROM game_tracking_reg g2 JOIN games USING (game_id) WHERE games.season_type <> 'REG'") == 0)
check("REG filter: August game IDs (e.g. 20240809xx) are all preseason",
      one("SELECT count(*) FROM games WHERE substr(game_id::varchar, 5, 2) = '08' AND season_type <> 'PRE'") == 0
      and one("SELECT count(*) FROM game_tracking_reg WHERE substr(game_id::varchar, 5, 2) = '08'") == 0)
check("REG filter: weeks 1-18 only",
      one("SELECT min(week) = 1 AND max(week) = 18 FROM game_tracking_reg"))

section(
    "player_play by season type",
    df("""SELECT g.season_type, count(*) AS rows FROM player_play JOIN games g USING (game_id)
          GROUP BY 1 ORDER BY 1"""),
    "player_play also includes PRE/POST; use the `player_play_reg` view.",
)
match = df("""WITH gp AS (SELECT DISTINCT game_id, play_id, nfl_id FROM game_tracking_reg)
              SELECT (SELECT count(*) FROM gp) AS tracked_player_plays,
                     (SELECT count(*) FROM gp JOIN player_play USING (game_id, play_id, nfl_id)) AS with_player_play_row,
                     (SELECT count(*) FROM player_play_reg) AS player_play_reg_rows""")
section("REG tracking <-> player_play overlap", match,
        "~1% of rows on either side have no partner; joins should be inner.")
check("REG tracking and player_play overlap >= 98%",
      match.with_player_play_row[0] / match.tracked_player_plays[0] >= 0.98)

# %% [markdown]
# ## 6. Exposure differs by draft class

# %%
section(
    "REG-season exposure by draft class x season",
    df("""SELECT p.draft_year, t.season, count(DISTINCT t.nfl_id) AS players,
                 count(DISTINCT (t.game_id, t.play_id, t.nfl_id)) AS player_plays
          FROM game_tracking_reg t JOIN players p USING (nfl_id) GROUP BY ALL ORDER BY 1, 2"""),
    "2023 class: three seasons; 2025 class: one. Normalize per snap/route and compare within class.",
)
section(
    "Players with any REG-season snap, by NFL position",
    df("""SELECT p.nfl_position, count(*) AS players, count(r.nfl_id) AS with_reg_snaps
          FROM players p LEFT JOIN (SELECT DISTINCT nfl_id FROM player_play_reg) r USING (nfl_id)
          GROUP BY 1 ORDER BY players DESC"""),
)

# %% [markdown]
# ## 7. WR focus: routes, targets, separation

# %%
section(
    "WRs: REG-season routes and separation coverage by draft class",
    df("""WITH r AS (SELECT nfl_id, count(route_ran) AS routes, sum(target::int) AS targets,
                            count(separation_at_pass_forward) AS sep_obs
                     FROM player_play_reg GROUP BY 1)
          SELECT p.draft_year, count(*) AS wrs, count(r.nfl_id) AS with_reg_snaps,
                 count(*) FILTER (WHERE routes >= 100) AS "100+ routes",
                 count(*) FILTER (WHERE routes >= 300) AS "300+ routes",
                 median(coalesce(routes, 0)) AS median_routes,
                 sum(routes) AS routes, sum(targets) AS targets, sum(sep_obs) AS separation_obs
          FROM players p LEFT JOIN r USING (nfl_id) WHERE p.nfl_position = 'WR'
          GROUP BY 1 ORDER BY 1"""),
    "`separation_at_pass_forward` is recorded on ~85% of routes (targeted or not), "
    "so it works as a per-route outcome, not just per target.",
)
section(
    "WR routes by type (REG)",
    df("""SELECT route_ran, count(*) AS routes, round(avg(separation_at_pass_forward), 2) AS mean_sep
          FROM player_play_reg pp JOIN players p USING (nfl_id)
          WHERE p.nfl_position = 'WR' AND route_ran IS NOT NULL GROUP BY 1 ORDER BY 2 DESC"""),
)

# %% [markdown]
# ## 8. Kinematics conventions (combine vs. game) — matters for Phase 1

# %%
conv = []
for name, src, part in [
    ("combine", "(SELECT * FROM combine_tracking WHERE entity_type = 'PLAYER')", "event_id"),
    ("game (2025 REG)", "(SELECT * FROM game_tracking_reg WHERE season = 2025)", "game_id, play_id, nfl_id"),
]:
    conv.append(df(f"""
        WITH t AS (SELECT *, lead(x) OVER w - x AS dx, lead(y) OVER w - y AS dy
                   FROM {src} WINDOW w AS (PARTITION BY {part} ORDER BY time))
        SELECT '{name}' AS source,
               median(abs(((dir - degrees(atan2(dx, dy))) + 540) % 360 - 180)) AS dir_err_deg,
               median(abs(s - 10 * sqrt(dx * dx + dy * dy))) AS speed_vs_disp_err,
               count(*) FILTER (WHERE a < 0) AS negative_a_frames
        FROM t WHERE s > 2 AND dx IS NOT NULL"""))
conv = pd.concat(conv)
section(
    "Direction / speed / acceleration conventions",
    conv,
    "`dir` is degrees clockwise from +y in both sources, and `s` matches frame displacement. "
    "`a` is an unsigned magnitude in both (the few negatives in game data are glitches), "
    "so deceleration must be derived from smoothed speed. Combine tracking has no `o`.",
)
check("dir convention matches in combine and game tracking (median error < 5 deg)", (conv.dir_err_deg < 5).all())

# %%
report[4:4] = ["## Checks", "", *checks, ""]
out = ROOT / "reports" / "00_audit.md"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text("\n".join(report))
print(f"\n{len(checks)} checks passed; wrote {out.relative_to(ROOT)}")
