# %% [markdown]
# # Phase 1 — combine cut features
#
# Detects cuts in every WR position-drill rep and every shuttle / 3-cone rep,
# validates the detector, measures how reliable each player-level feature is,
# and writes:
#
# - `data/features/combine_cuts.parquet`            one row per detected cut
# - `data/features/combine_player_features.parquet` one row per player
# - `reports/01_combine_features.md` + `reports/figures/01_*.png`
#
# Every `check(...)` is a hard assertion. Uses combine data only; no NFL outcomes.
#
# Run: `python notebooks/01_combine_features.py`

# %%
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import matplotlib  # noqa: E402

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402
from matplotlib.collections import LineCollection  # noqa: E402
from matplotlib.colors import LinearSegmentedColormap  # noqa: E402

from src import cuts as C  # noqa: E402
from src import features as F  # noqa: E402
from src.data import connect  # noqa: E402

FEATURES = ROOT / "data" / "features"
FIGURES = ROOT / "reports" / "figures"
FEATURES.mkdir(parents=True, exist_ok=True)
FIGURES.mkdir(parents=True, exist_ok=True)

con = connect()
report: list[str] = ["# Phase 1 — combine cut features", "",
                     "Generated by `notebooks/01_combine_features.py`. Do not edit by hand.", ""]
checks: list[str] = []


def check(name: str, ok: bool, detail: str = "") -> None:
    checks.append(f"- [{'x' if ok else ' '}] {name}" + (f" — {detail}" if detail else ""))
    assert ok, f"{name}: {detail}"


def md_table(d: pd.DataFrame, index: bool = False) -> str:
    if index:
        d = d.reset_index()

    def fmt(v):
        if isinstance(v, str):
            return v.replace("|", "\\|")  # slot names contain "|"
        if pd.isna(v):
            return ""
        if isinstance(v, (int, np.integer)) or (isinstance(v, float) and v == int(v) and abs(v) >= 10):
            return f"{int(v):,}"
        return f"{v:.2f}"

    rows = ["| " + " | ".join(map(str, d.columns)) + " |", "|" + "---|" * d.shape[1]]
    rows += ["| " + " | ".join(fmt(v) for v in r) + " |" for r in d.itertuples(index=False)]
    return "\n".join(rows)


def section(title: str, d: pd.DataFrame | None = None, note: str = "", index: bool = False) -> None:
    report.extend([f"## {title}", ""])
    if note:
        report.extend([note, ""])
    if d is not None:
        report.extend([md_table(d, index), ""])
    print(f"\n== {title}\n{'' if d is None else d.to_string()}")


# Chart styling: reference palette (dataviz skill), recessive axes.
SERIES = ["#2a78d6", "#eb6834", "#1baf7a"]
INK, INK2, GRID = "#0b0b0b", "#52514e", "#e4e3df"
plt.rcParams.update({
    "figure.facecolor": "#fcfcfb", "axes.facecolor": "#fcfcfb", "savefig.facecolor": "#fcfcfb",
    "axes.edgecolor": GRID, "axes.labelcolor": INK2, "xtick.color": INK2, "ytick.color": INK2,
    "axes.titlecolor": INK, "axes.titlesize": 10, "axes.labelsize": 9, "xtick.labelsize": 8, "ytick.labelsize": 8,
    "axes.spines.top": False, "axes.spines.right": False, "axes.grid": True, "grid.color": GRID,
    "grid.linewidth": 0.6, "lines.linewidth": 2, "font.size": 9,
})

# %% [markdown]
# ## 1. Detect cuts

# %%
report.extend([
    "## Method", "",
    "- x/y are smoothed with a Savitzky–Golay filter (0.7 s, quadratic); velocity and acceleration come "
    "from its derivatives, split into along-track (braking / re-acceleration) and lateral (turning) parts. "
    "The same code will run on game routes in Phase 2.",
    "- A **cut** is a peak of at least 30° in the turn between the velocity 0.5 s before and 0.5 s after a frame. "
    "Its **apex** is the slowest frame near that peak. Cuts need ≥ 2 yd/s going in and ≥ 1.5 yd/s coming out.",
    "- Per cut: speed into the break (max over the prior 1.5 s), apex speed, speed retention (apex / entry), "
    "peak braking, distance used to slow down, peak lateral acceleration, speed regained 0.5 s after the apex.",
    "- Each metric is z-scored within its **slot** (the same break of the same drill across players, e.g. "
    "the curl's plant). A player's feature is their mean z, so players who ran different drills are comparable.",
    "",
])

frames = con.sql(
    """SELECT event_id, nfl_id, drill_type, drill_name, time, x, y, s FROM combine_tracking
       WHERE entity_type = 'PLAYER' AND drill_type IN ('SKILL_DRILLS_WR', 'SHORT_SHUTTLE', 'THREE_CONE_DRILL')
       ORDER BY event_id, time"""
).df()
err = np.concatenate([
    np.abs(C.kinematics(r.x.to_numpy(), r.y.to_numpy())["speed"] - r.s.to_numpy())
    for _, r in frames.groupby("event_id")
])
check("smoothed speed matches the provided `s`", np.median(err) < 0.1,
      f"median |diff| {np.median(err):.3f} yd/s, 95th pct {np.quantile(err, 0.95):.2f}")

pos_cuts = F.combine_cuts(con, F.POSITION_DRILLS)
agl_cuts = F.combine_cuts(con, F.AGILITY_DRILLS)
reps = frames.drop_duplicates("event_id").set_index("event_id")[["nfl_id", "drill_type", "drill_name"]]
all_cuts = pd.concat([pos_cuts, agl_cuts])
n_cuts = all_cuts.groupby("event_id").size().reindex(reps.index, fill_value=0)

per_rep = pd.crosstab(reps.drill_name, n_cuts.clip(upper=4).map(lambda k: f"{k}+" if k == 4 else str(k)))
per_rep.insert(0, "reps", per_rep.sum(axis=1))
section("Cuts detected per rep", per_rep, index=True,
        note="Straight-line drills (go route, over-the-shoulder, red-zone fade) should have none; "
             "the shuttle has two reversals; the 3-cone has two reversals plus three bends around cones.")

shuttle = reps.drill_name == "SHORT_SHUTTLE"
sharp = agl_cuts[agl_cuts.turn_deg >= 150].groupby("event_id").size().reindex(reps.index[shuttle], fill_value=0)
check("shuttle: most reps have exactly two ≥150° reversals", (sharp == 2).mean() >= 0.8,
      f"{(sharp == 2).mean():.0%} of {shuttle.sum()} reps")
go = reps.drill_name == "GO_ROUTE_RIGHT"
check("go route: no cuts on a straight sprint", (n_cuts[go] == 0).mean() >= 0.95,
      f"{(n_cuts[go] == 0).mean():.0%} of {go.sum()} reps")
check("3-cone: median of ≥ 4 cuts per rep",
      n_cuts[reps.drill_name == "THREE_CONE_DRILL"].median() >= 4)

# Turn direction must match route semantics (receiver's side of the formation).
# Reps with no detected cut count as misses, so missed detections can't hide.
first_dir = (pos_cuts.sort_values("apex_frame").groupby("event_id")["turn_dir"].first()
             .reindex(reps.index))
expect = {"CURL_ROUTE_RIGHT": "L", "COMEBACK_ROUTE_RIGHT": "R", "SLANT_ROUTE_LEFT": "R",
          "SPEED_OUT_ROUTE_LEFT": "L", "DAGGER_ROUTE_LEFT": "R", "SLOT_SAIL_ROUTE_RIGHT": "R"}
sem = pd.DataFrame([
    {"drill": d, "expected first break": f"{'left' if e == 'L' else 'right'}",
     "reps": int((reps.drill_name == d).sum()),
     "no cut detected": int(first_dir[reps.drill_name == d].isna().sum()),
     "share matching": (first_dir[reps.drill_name == d] == e).mean()}
    for d, e in expect.items()
])
section("First break direction vs route", sem,
        note="A right-side curl breaks back inside (left), a right-side comeback breaks to the sideline (right), "
             "a left-side slant breaks inside (right), and so on. Agreement confirms the left/right sign. "
             "Reps with no detected cut count as misses.")
check("first-break direction matches the route in ≥ 90% of reps, every route",
      (sem["share matching"] >= 0.9).all(), f"min {sem['share matching'].min():.0%}")

# %% [markdown]
# ## 2. Slot scoring and per-slot summaries

# %%
pos_z = F.slot_z(pos_cuts, by_direction=True)
agl_z = F.slot_z(agl_cuts, by_direction=False)
slot_tab = pos_z.groupby("slot").agg(
    cuts=("event_id", "size"), turn_deg=("turn_deg", "median"), entry_speed=("entry_speed", "median"),
    apex_speed=("apex_speed", "median"), retention=("speed_retention", "median"),
    peak_decel=("peak_decel", "median"), lat_accel=("peak_lat_accel", "median"),
    apex_time_s=("apex_frame", lambda s: s.median() * C.DT))
section("WR drill slots (medians)", slot_tab, index=True,
        note=f"{len(pos_z):,} of {len(pos_cuts):,} WR drill cuts fall in slots with ≥ {F.MIN_CUTS_PER_SLOT} cuts. "
             "Speeds in yd/s, accelerations in yd/s².")

# %% [markdown]
# ## 3. Does the detector measure agility? Shuttle / 3-cone features vs official times

# %%
cr = con.sql("""SELECT c.nfl_id, c.combine_position, c.forty, c.ten_yd_split, c.three_cone, c.short_shuttle,
                       c.combine_weight, c.combine_height, c.vertical, c.broad_jump
                FROM combine_results c""").df().set_index("nfl_id")
rows = []
for drill, official in [("SHORT_SHUTTLE", "short_shuttle"), ("THREE_CONE_DRILL", "three_cone")]:
    f = F.player_features(agl_z[agl_z.drill_name == drill], "f").join(cr)
    f = f[f[official].notna()]
    rows.append({"drill": drill, "players": len(f),
                 **{m: f[f"f_{m}"].corr(f[official]) for m in F.METRICS}})
validity = pd.DataFrame(rows)
section("Tracking features vs official stopwatch time (Pearson r)", validity,
        note="Negative = more of the feature goes with a faster official time. Players of all positions with both.")
for _, r in validity.iterrows():
    check(f"{r.drill}: harder braking goes with a faster official time", r.peak_decel <= -0.3, f"r = {r.peak_decel:.2f}")

# %% [markdown]
# ## 4. WR features: reliability

# %%
feats = F.player_features(pos_z, "pos").join(F.player_features(agl_z, "agl"), how="outer")
feats = cr[["combine_position"]].join(feats, how="inner")
rel = F.split_half_reliability(pos_z, n_iter=200)
kind = {"": "mean", "_lr": "left − right", "_sd": "consistency (SD)"}
rel["metric"] = rel.feature.str.replace(r"_(lr|sd)$", "", regex=True)
rel["kind"] = rel.feature.str.extract(r"(_lr|_sd)$")[0].fillna("").map(kind)
rel_tab = rel.pivot(index="metric", columns="kind", values="reliability").loc[list(F.METRICS),
                                                                              list(kind.values())]
section("Split-half reliability of WR position-drill features",
        rel_tab, index=True,
        note=f"{rel.players.iloc[0]} WRs with ≥ 4 drills; median over 200 random drill splits, Spearman–Brown "
             "corrected. Roughly: < 0.3 mostly noise, 0.5 usable with shrinkage, > 0.7 solid. "
             "Left − right is confounded with drill (each route breaks a fixed way) and consistency "
             "needs repeat reps the combine doesn't have; neither measures a stable trait here.")
PRIMARY = ["entry_speed", "speed_retention", "peak_lat_accel"]
check("pre-registered WR features have split-half reliability ≥ 0.45",
      (rel_tab.loc[PRIMARY, "mean"] >= 0.45).all(),
      ", ".join(f"{m} {rel_tab.loc[m, 'mean']:.2f}" for m in PRIMARY))

# %% [markdown]
# ## 5. WR features vs the stopwatch and each other

# %%
stop = ["forty", "ten_yd_split", "three_cone", "short_shuttle", "vertical", "broad_jump", "combine_weight",
        "combine_height"]
wr = feats[feats.combine_position == "WR"].join(cr[stop])
cols = [f"pos_{m}" for m in F.METRICS]
vs = pd.DataFrame({c: [wr[f].corr(wr[c]) for f in cols] for c in stop}, index=list(F.METRICS))
section("WR features vs standard combine results (Pearson r)", vs, index=True,
        note=f"{len(wr)} WRs; 3-cone and shuttle times exist for only ~1/3 of them. Small |r| against the "
             "40 means the cut features are not just straight-line speed again.")
section("WR feature intercorrelations", wr[cols].corr().set_axis(list(F.METRICS)).set_axis(list(F.METRICS), axis=1),
        index=True)

# %% [markdown]
# ## 6. Figures

# %%
# Figure 1: anatomy of one cut — a typical curl plant.
curl = pos_z[pos_z.slot == "CURL_ROUTE_RIGHT|L1"].copy()
curl["dist"] = curl[[f"{m}_z" for m in PRIMARY]].abs().sum(axis=1)
ex = curl.nsmallest(1, "dist").iloc[0]
r = frames[frames.event_id == ex.event_id]
k = C.kinematics(r.x.to_numpy(), r.y.to_numpy())
x, y = r.x.to_numpy() - r.x.iloc[0], r.y.to_numpy() - r.y.iloc[0]
# Rotate so the stem runs up the page.
ang = np.arctan2(x[15], y[15])
x, y = np.cos(ang) * x - np.sin(ang) * y, np.sin(ang) * x + np.cos(ang) * y
t = np.arange(len(r)) * C.DT
apex = int(ex.apex_frame)
entry = max(apex - C.ENTRY_WINDOW, 0) + int(np.argmax(k["speed"][max(apex - C.ENTRY_WINDOW, 0):apex + 1]))
after = apex + C.GAIN_FRAMES

fig, (ax0, ax1) = plt.subplots(1, 2, figsize=(10, 4.6), gridspec_kw={"width_ratios": [1, 1.6]})
pts = np.column_stack([x, y]).reshape(-1, 1, 2)
# Single-hue ramp, trimmed so the slowest frames stay visible on the light surface.
blues = LinearSegmentedColormap.from_list("blues", plt.get_cmap("Blues")(np.linspace(0.3, 1, 256)))
lc = LineCollection(np.concatenate([pts[:-1], pts[1:]], axis=1), cmap=blues, linewidth=3,
                    norm=plt.Normalize(0, k["speed"].max()))
lc.set_array(k["speed"][:-1])
ax0.add_collection(lc)
for i, label, off, ha in [(entry, "entry", (10, 0), "left"), (apex, "apex", (10, 4), "left"),
                          (after, "+0.5 s", (0, -16), "center")]:
    ax0.plot(x[i], y[i], "o", ms=8, mfc="#fcfcfb", mec=INK, mew=1.5)
    ax0.annotate(label, (x[i], y[i]), xytext=off, textcoords="offset points", color=INK, fontsize=9,
                 va="center", ha=ha)
ax0.set_aspect("equal")
ax0.autoscale()
ax0.margins(0.25)
ax0.set_title("Path (darker = faster)", loc="left")
ax0.set_xlabel("yards")
cb = fig.colorbar(lc, ax=ax0, shrink=0.7)
cb.set_label("speed (yd/s)", color=INK2)
cb.outline.set_visible(False)

ax1.plot(t, k["speed"], color=SERIES[0])
ax1.axvspan(t[entry], t[apex], color=GRID, alpha=0.6, lw=0)
for i, label in [(entry, f"entry {ex.entry_speed:.1f} yd/s"), (apex, f"apex {ex.apex_speed:.1f} yd/s"),
                 (after, f"+{ex.reaccel_gain:.1f} yd/s in 0.5 s")]:
    ax1.plot(t[i], k["speed"][i], "o", ms=8, mfc="#fcfcfb", mec=SERIES[0], mew=1.5)
    ax1.annotate(label, (t[i], k["speed"][i]), xytext=(8, 6), textcoords="offset points", color=INK, fontsize=9)
ax1.annotate(f"braking: peak {ex.peak_decel:.1f} yd/s²\nretention {ex.speed_retention:.0%}",
             ((t[entry] + t[apex]) / 2, 0.4), ha="center", color=INK2, fontsize=9)
ax1.set_xlabel("seconds into rep")
ax1.set_ylabel("speed (yd/s)")
ax1.set_ylim(bottom=0)
ax1.set_title("Speed through the break", loc="left")
fig.suptitle("Anatomy of a cut: a typical curl plant at the combine", x=0.01, ha="left", color=INK, fontsize=12)
fig.tight_layout()
fig.savefig(FIGURES / "01_cut_anatomy.png", dpi=110)
plt.close(fig)

# Figure 2: detected cuts on sample reps of every WR drill.
drills = sorted(pos_cuts.drill_name.unique())
rng = np.random.default_rng(7)
fig, axes = plt.subplots(3, 5, figsize=(15, 9.5))
for ax, d in zip(axes.ravel(), drills):
    evs = reps.index[reps.drill_name == d]
    for col, ev in zip(SERIES, rng.choice(evs, 3, replace=False)):
        rr = frames[frames.event_id == ev]
        xx, yy = rr.x.to_numpy() - rr.x.iloc[0], rr.y.to_numpy() - rr.y.iloc[0]
        a = np.arctan2(xx[15], yy[15])
        xx, yy = np.cos(a) * xx - np.sin(a) * yy, np.sin(a) * xx + np.cos(a) * yy
        ax.plot(xx, yy, color=col, lw=1.5)
        ap = pos_cuts.loc[pos_cuts.event_id == ev, "apex_frame"].astype(int)
        ax.plot(xx[ap], yy[ap], "o", ms=8, mfc="#fcfcfb", mec=col, mew=1.5)
    ax.set_aspect("equal", "datalim")
    ax.set_title(d.replace("_", " ").title(), fontsize=9, loc="left")
    ax.tick_params(labelsize=7)
for ax in axes.ravel()[len(drills):]:
    ax.remove()
fig.suptitle("Detected cut apexes (circles) on three random reps per WR drill; every path starts at (0, 0) "
             "heading up the page", x=0.01, ha="left", color=INK, fontsize=11)
fig.tight_layout()
fig.savefig(FIGURES / "01_cut_examples.png", dpi=90)
plt.close(fig)

report.extend([
    "## Figures", "",
    "![Anatomy of a cut](figures/01_cut_anatomy.png)", "",
    "![Detected cuts on sample reps](figures/01_cut_examples.png)", "",
])

# %%
pd.concat([pos_z, agl_z]).to_parquet(FEATURES / "combine_cuts.parquet", index=False)
feats.to_parquet(FEATURES / "combine_player_features.parquet")
report[4:4] = ["## Checks", "", *checks, ""]
out = ROOT / "reports" / "01_combine_features.md"
out.write_text("\n".join(report))
print(f"\n{len(checks)} checks passed; {len(feats)} players; wrote {out.relative_to(ROOT)}")
