# %% [markdown]
# # Phase 2 — game cut features and outcomes
#
# Runs the Phase 1 cut detector, unchanged, on every regular-season WR route,
# validates it against route semantics, scores each break against breaks of the
# same route type, side, depth and angle, measures how stable each player-level
# game feature and outcome is, and writes:
#
# - `data/features/game_cuts.parquet`    one row per in-game route break, with scores
# - `data/features/game_routes.parquet`  one row per WR route, with expected separation
# - `data/features/wr_analysis.parquet`  one row per WR: draft, baseline tests, combine and game features, outcomes
# - `reports/02_game_features.md` + `reports/figures/02_*.png`
#
# Every `check(...)` is a hard assertion. Phase 2 computes no correlation between combine
# features and game data, or between cut features and outcomes: those are Phase 3's
# pre-registered tests.
#
# Run: `python notebooks/02_game_features.py` (after `notebooks/01_combine_features.py`)

# %%
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import matplotlib  # noqa: E402

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402
from matplotlib.lines import Line2D  # noqa: E402

from src import cuts as C  # noqa: E402
from src import features as F  # noqa: E402
from src import outcomes as O  # noqa: E402
from src import routes as R  # noqa: E402
from src.data import connect  # noqa: E402
from src.stats import detectable_r, split_half  # noqa: E402

FEATURES = ROOT / "data" / "features"
FIGURES = ROOT / "reports" / "figures"
FIGURES.mkdir(parents=True, exist_ok=True)
if not (FEATURES / "combine_player_features.parquet").exists():
    raise SystemExit("Run notebooks/01_combine_features.py first: Phase 2 joins its combine features.")

con = connect()
report: list[str] = ["# Phase 2 — game cut features and outcomes", "",
                     "Generated by `notebooks/02_game_features.py`. Do not edit by hand.", ""]
checks: list[str] = []


def check(name: str, ok: bool, detail: str = "") -> None:
    checks.append(f"- [{'x' if ok else ' '}] {name}" + (f" — {detail}" if detail else ""))
    assert ok, f"{name}: {detail}"


def md_table(d: pd.DataFrame, index: bool = False) -> str:
    if index:
        d = d.reset_index()

    def fmt(v):
        if isinstance(v, str):
            return v
        if pd.isna(v):
            return ""
        if isinstance(v, (int, np.integer)) or (isinstance(v, float) and v == int(v) and abs(v) >= 10):
            return f"{int(v):,}"
        return f"{round(float(v), 2) + 0.0:.2f}"  # + 0.0 turns -0.00 into 0.00

    rows = ["| " + " | ".join(map(str, d.columns)) + " |", "|" + "---|" * d.shape[1]]
    rows += ["| " + " | ".join(fmt(v) for v in r) + " |" for r in d.itertuples(index=False)]
    return "\n".join(rows)


def section(title: str, d: pd.DataFrame | None = None, note: str = "", index: bool = False) -> None:
    report.extend([f"## {title}", ""])
    if note:
        report.extend([note, ""])
    if d is not None:
        report.extend([md_table(d, index), ""])
    print(f"\n== {title}\n{'' if d is None else d.to_string()}")


def pct(v: float) -> str:
    return "" if pd.isna(v) else f"{v:.0%}"


# Chart styling: reference palette (dataviz skill), recessive axes. Same as Phase 1.
SERIES = ["#2a78d6", "#eb6834", "#1baf7a"]
SURFACE, INK, INK2, GRID = "#fcfcfb", "#0b0b0b", "#52514e", "#e4e3df"
plt.rcParams.update({
    "figure.facecolor": SURFACE, "axes.facecolor": SURFACE, "savefig.facecolor": SURFACE,
    "axes.edgecolor": GRID, "axes.labelcolor": INK2, "xtick.color": INK2, "ytick.color": INK2,
    "axes.titlecolor": INK, "axes.titlesize": 10, "axes.labelsize": 9, "xtick.labelsize": 8, "ytick.labelsize": 8,
    "axes.spines.top": False, "axes.spines.right": False, "axes.grid": True, "grid.color": GRID,
    "grid.linewidth": 0.6, "lines.linewidth": 2, "font.size": 9,
})

PRIMARY = ["entry_speed", "speed_retention", "peak_lat_accel"]  # pre-registered in Phase 1
NAMES = {"entry_speed": "speed into the break", "speed_retention": "speed retention (apex / entry)",
         "peak_lat_accel": "peak lateral (turning) acceleration", "peak_decel": "peak braking (secondary)"}
EXPECT = {"SLANT": "in", "IN": "in", "POST": "in", "CROSS": "in", "OUT": "out", "CORNER": "out"}

report.extend([
    "## Method", "",
    "- **Routes:** every WR route in a regular-season play (penalty-nullified plays dropped). The window runs "
    "from the snap to 1 s after the throw, both taken from the receiver's own tracking event tags.",
    "- **Cuts:** the Phase 1 detector runs unchanged, so game and combine breaks get identical smoothing, "
    "thresholds and metrics. A cut counts as a route break if its apex comes no later than 0.5 s after the throw "
    "(on timing routes the QB releases before the break) and at least 1 yd past the receiver's snap position "
    "(shallower turns are release moves at the line). Screens are left out: they have no route break.",
    "- **Break side:** `in` turns toward the middle of the field, `out` toward the sideline. The ball isn't tracked, "
    "so the middle of the field stands in for it.",
    "- **Scores:** slot = route × break side. Game breaks in a slot still differ in depth and angle (a 5-yd quick "
    "out vs a 12-yd deep out), which drives speed and retention. So within each slot every metric is regressed on "
    "depth and turn angle (with squares), and the standardized residual is the break's score. A player's game "
    "feature is the mean score over their breaks, the same construction as the combine features.",
    "- **Outcomes:** separation at the throw minus the cohort average for the same route, coverage (man / zone) "
    "and time to throw = separation over expected (SOE). Usage and production: target rate, yards per route run.",
    "- **Reliability:** split-half across games (each player's games split at random, 200 times, "
    "Spearman–Brown corrected), for WRs with at least 6 games.",
    "",
])

# %% [markdown]
# ## 1. Route windows

# %%
routes = R.wr_routes(con)
has_window = routes.t_snap.notna() & routes.t_pass.notna()
frames = R.route_frames(con, routes)
win = pd.DataFrame({"routes": [
    len(routes), routes.t_snap.notna().sum(), routes.t_pass.notna().sum(), has_window.sum(),
    frames.groupby(R.KEY).ngroups,
]}, index=["WR routes in regular-season plays", "with a snap tag in the receiver's tracking",
           "with a throw (pass_forward) tag", "route windows (both tags)", "route windows with frames"]).rename_axis("step")
section("Route windows", win, index=True,
        note=f"Plays without a throw tag are mostly sacks and scrambles. Median time to throw "
             f"{routes.ttt.median():.1f} s; {len(frames):,} frames in the windows.")
check("≥ 99% of WR routes have a snap tag in the receiver's own tracking",
      routes.t_snap.notna().mean() >= 0.99, pct(routes.t_snap.notna().mean()))

sample = frames[R.KEY].drop_duplicates().sample(2000, random_state=0)
err = np.concatenate([
    np.abs(C.kinematics(g.x.to_numpy(), g.y.to_numpy())["speed"] - g.s.to_numpy())
    for _, g in frames.merge(sample, on=R.KEY).groupby(R.KEY) if len(g) > 2 * C.HALF_WINDOW
])
check("smoothed speed matches the provided `s` on game routes", np.median(err) < 0.1,
      f"median |diff| {np.median(err):.3f} yd/s over 2,000 random routes, 95th pct {np.quantile(err, 0.95):.2f}")

# %% [markdown]
# ## 2. Does the combine detector find real route breaks in games?

# %%
cuts = R.route_cuts(frames, routes)
kept = cuts[cuts.kept].copy()
n_win = routes[has_window].groupby("route_ran").size().drop(list(R.EXCLUDED_ROUTES))
first = kept.sort_values([*R.KEY, "apex_frame"]).groupby(R.KEY).first()
fg = first.groupby("route_ran")
per_route = pd.DataFrame({
    "routes": n_win,
    "with a break": (fg.size() / n_win).map(pct),
    "breaks per route": kept.groupby("route_ran").size() / n_win,
    "1st break: depth (yd)": fg.depth.median(),
    "1st break: turn (deg)": fg.turn_deg.median(),
    "1st break: s after snap": fg.t_after_snap.median(),
    "expected side": pd.Series(EXPECT),
    "1st break on expected side": fg.apply(lambda d: (d.break_side == EXPECT.get(d.name)).mean()
                                           if d.name in EXPECT else np.nan, include_groups=False).map(pct),
}).sort_values("routes", ascending=False).fillna({"expected side": "—"}).rename_axis("route")
section("Breaks found per route type", per_route, index=True,
        note=f"{len(kept):,} of {len(cuts):,} detected cuts count as route breaks. Rounded breaks (many posts, "
             "corners and crossers) turn less than the detector's 30° in 0.5 s and aren't counted; hitches often "
             "end with the receiver settling rather than coming back. Routes with known geometry break the "
             "expected way, which validates both the detector and the in / out labels.")
side_ok = fg.apply(lambda d: (d.break_side == EXPECT[d.name]).mean() if d.name in EXPECT else np.nan,
                   include_groups=False).dropna()
check("first break goes the route's way (in: slant, in, post, cross; out: out, corner) in ≥ 80% of routes, "
      "every route", (side_ok >= 0.8).all(), ", ".join(f"{k} {v:.0%}" for k, v in side_ok.items()))

late = kept[(kept.t_after_throw > 0) & kept.route_ran.isin(list(EXPECT))]
late_first = late.sort_values([*R.KEY, "apex_frame"]).groupby(R.KEY).first()
late_ok = (late_first.break_side == late_first.route_ran.map(EXPECT)).mean()
check("breaks in the 0.5 s after the throw still go the route's way (≥ 85%): route breaks, not adjustments "
      "to the ball", late_ok >= 0.85, f"{late_ok:.0%} of {len(late_first):,} routes")

# %% [markdown]
# ## 3. Scoring breaks within slots

# %%
zc = R.slot_z_adjusted(kept)
zcols = [f"{m}_z" for m in R.METRICS]
slot_tab = zc.groupby("slot").agg(
    breaks=("slot", "size"), depth=("depth", "median"), turn_deg=("turn_deg", "median"),
    entry_speed=("entry_speed", "median"), retention=("speed_retention", "median"),
    lat_accel=("peak_lat_accel", "median"), braking=("peak_decel", "median"),
).sort_values("breaks", ascending=False)
section("Game slots (medians)", slot_tab, index=True,
        note=f"{len(zc):,} of {len(kept):,} route breaks fall in slots with ≥ {R.MIN_CUTS_PER_SLOT} breaks. "
             "Depth in yd downfield from the snap position; speeds in yd/s; accelerations in yd/s².")

plain = {m: (zc[m] - zc.groupby("slot")[m].transform("mean")) / zc.groupby("slot")[m].transform("std")
         for m in R.METRICS}
adj = pd.DataFrame({
    "depth: slot z": [plain[m].corr(zc.depth) for m in R.METRICS],
    "depth: adjusted": [zc[f"{m}_z"].corr(zc.depth) for m in R.METRICS],
    "turn: slot z": [plain[m].corr(zc.turn_deg) for m in R.METRICS],
    "turn: adjusted": [zc[f"{m}_z"].corr(zc.turn_deg) for m in R.METRICS],
}, index=[NAMES[m] for m in R.METRICS]).rename_axis("metric")
section("Correlation of break scores with depth and turn angle (Pearson r)", adj, index=True,
        note="Plain within-slot z-scores still carry route depth (deeper breaks are run faster) and angle "
             "(sharper breaks keep less speed). The adjusted scores don't.")
check("adjusted scores are uncorrelated with depth and turn angle (|r| < 0.05)",
      bool((adj[["depth: adjusted", "turn: adjusted"]].abs() < 0.05).all().all()))

# %% [markdown]
# ## 4. Are game cut features stable player traits?

# %%
gfeat = R.player_features(zc)
rel_all = split_half(zc, zcols).set_index("feature")
rel_main = split_half(R.main_breaks(zc), zcols).set_index("feature")
rel_game = pd.DataFrame({
    "all route breaks (primary)": rel_all.reliability.values,
    "main break only": rel_main.reliability.values,
}, index=[NAMES[m] for m in R.METRICS]).rename_axis("metric")
section("Split-half reliability of WR game cut features", rel_game, index=True,
        note=f"{rel_all.players.iloc[0]} WRs with ≥ 6 games (median {zc.groupby('nfl_id').size().median():.0f} "
             "breaks per WR). Main break only = each route's first break on its designed side (hitches: first "
             "break), a sensitivity check closest to a drill rep. Roughly: < 0.3 mostly noise, 0.5 usable with "
             "shrinkage, > 0.7 solid.")
check("game speed into the break is a stable player trait (split-half ≥ 0.6)",
      rel_all.reliability["entry_speed_z"] >= 0.6, f"{rel_all.reliability['entry_speed_z']:.2f}")

# %% [markdown]
# ## 5. Outcomes

# %%
sr = O.separation_routes(routes)
sep_tab = sr.pivot_table(index="route_ran", columns="coverage", values="separation", aggfunc="mean")
sep_tab = sep_tab[["MAN_COVERAGE", "ZONE_COVERAGE"]].rename(
    columns={"MAN_COVERAGE": "vs man", "ZONE_COVERAGE": "vs zone"}).rename_axis(None, axis=1)
sep_tab.insert(0, "routes", sr.groupby("route_ran").size())
sep_tab = sep_tab.rename_axis("route")
section("Mean separation at the throw (yd) by route and coverage",
        sep_tab.sort_values("routes", ascending=False), index=True,
        note=f"{len(sr):,} routes with separation and a throw time (screens left out). Expected-separation cells "
             f"(route × coverage × time-to-throw bin) explain {O.explained_variance(sr):.0%} of route-level "
             "variance; the rest is the receiver, the defender and the play.")

route_obs = routes.assign(target=routes.target.astype(float), yards=routes.rec_yards.fillna(0))
rel_out = pd.concat([split_half(sr, ["separation", "soe"]),
                     split_half(route_obs, ["target", "yards"])]).set_index("feature")
out_tab = pd.DataFrame({
    "per route": ["separation at the throw (yd)", "separation over expected (yd)", "targeted (0/1)",
                  "receiving yards"],
    "player value": ["mean separation", "SOE", "target rate", "yards per route run"],
    "split-half reliability": rel_out.reliability.values,
    "WRs (≥ 6 games)": rel_out.players.values,
}, index=["separation", "soe", "target_rate", "yprr"]).rename_axis("outcome")
section("Outcomes and their reliability", out_tab, index=True,
        note="Adjusting for route, coverage and time to throw lowers reliability: part of a WR's raw separation "
             "is their role (the coverage and routes they get). SOE is the fairer skill measure, but noisier.")

# %% [markdown]
# ## 6. One table per WR for Phase 3

# %%
players = con.sql("""SELECT nfl_id, display_name, draft_year, draft_round, draft_overall_pick
                     FROM players WHERE nfl_position = 'WR'""").df().set_index("nfl_id")
baseline = con.sql("""SELECT nfl_id, combine_position, forty, ten_yd_split, vertical, broad_jump,
                             combine_height, combine_weight, ngs_athleticism_score
                      FROM combine_results""").df().set_index("nfl_id")
cfeat = pd.read_parquet(FEATURES / "combine_player_features.parquet")
cfeat = cfeat[["pos_n_cuts", "pos_n_drills", *[f"pos_{m}" for m in F.METRICS]]]
pout = O.player_outcomes(routes, sr)
car = O.career(con)[["career_offensive_snaps", "career_games_active", "career_games_started"]]
games_with_breaks = zc.groupby("nfl_id").game_id.nunique().rename("game_n_games")
wr = players.join(baseline).join(cfeat).join(gfeat).join(games_with_breaks).join(pout).join(car)
wr.insert(wr.columns.get_loc("draft_overall_pick") + 1, "udfa", wr.draft_overall_pick.isna())

has_combine = wr.pos_entry_speed.notna()
enough_routes = wr.routes.fillna(0) >= 100
game_ok = wr.game_n_games.fillna(0) >= 6
cov = pd.DataFrame({"WRs": [len(wr), has_combine.sum(), enough_routes.sum(), game_ok.sum(),
                            (has_combine & game_ok).sum(), (has_combine & enough_routes).sum()]},
                   index=["WRs in the cohort", "with combine WR-drill features", "with ≥ 100 regular-season routes",
                          "with game cut features from ≥ 6 games", "with combine features and game features "
                          "from ≥ 6 games", "with combine features and ≥ 100 routes"]).rename_axis("group")
section("Who is in the Phase 3 table", cov, index=True)
check("every WR with ≥ 100 regular-season routes has game cut features and SOE",
      bool(wr.loc[enough_routes, ["game_entry_speed", "soe"]].notna().all().all()))

# %% [markdown]
# ## 7. What Phase 3 can detect (reliability only, no linkage)

# %%
ccuts = pd.read_parquet(FEATURES / "combine_cuts.parquet")
crel = F.split_half_reliability(ccuts[ccuts.drill_type == "SKILL_DRILLS_WR"], n_iter=200,
                                metrics=tuple(R.METRICS)).set_index("feature").reliability
n_link1 = int((has_combine & game_ok).sum())
soe_ok = wr.index.isin(sr.groupby("nfl_id").game_id.nunique().loc[lambda s: s >= 6].index)
n_soe = int((has_combine & soe_ok).sum())
rows = []
for m in R.METRICS:
    rows.append(("combine → game", NAMES[m], crel[m], rel_all.reliability[f"{m}_z"], n_link1))
for m in PRIMARY:
    rows.append(("combine → SOE", NAMES[m], crel[m], rel_out.reliability["soe"], n_soe))
det = pd.DataFrame(rows, columns=["link", "combine signal", "combine reliability", "game-side reliability", "WRs"])
det["ceiling on observed r"] = np.sqrt(det["combine reliability"].clip(lower=0) * det["game-side reliability"].clip(lower=0))
det["smallest detectable observed r"] = det.WRs.map(detectable_r)
true_r = det["smallest detectable observed r"] / det["ceiling on observed r"]
det["smallest detectable true r"] = true_r.map(lambda v: f"{v:.2f}" if v <= 1 else "> 1 (not detectable)")
section("Detectability of Phase 3's player-level tests", det,
        note="Measurement noise caps any observed correlation at √(reliability × reliability). With the WRs "
             "available, a two-sided test at α = 0.05 with 80% power needs the observed |r| in the 6th column, "
             "so the true correlation has to be at least the last column. This uses reliabilities only: no combine "
             "feature has been correlated with game data or outcomes. Route-level models of SOE (tens of "
             "thousands of routes, player random effects) are not limited the same way.")

# %% [markdown]
# ## 8. Figure

# %%
show = ["SLANT", "IN", "POST", "CROSS", "OUT", "CORNER", "HITCH", "GO"]
win_routes = routes[has_window]
fr = frames.set_index(R.KEY).sort_index()
kept_by = {k: g for k, g in kept.groupby(R.KEY)}
fig, axes = plt.subplots(2, 4, figsize=(14, 8.4))
for ax, rt in zip(axes.ravel(), show):
    for _, rr in win_routes[win_routes.route_ran == rt].sample(12, random_state=3).iterrows():
        key = (rr.game_id, rr.play_id, rr.nfl_id)
        g = fr.loc[key]
        t = (g.time - rr.t_snap).dt.total_seconds().to_numpy()
        n = int((t <= rr.ttt + R.MAX_AFTER_THROW + 1e-9).sum())
        x, y = g.x.to_numpy()[:n], g.y.to_numpy()[:n]
        d = 1.0 if rr.play_direction == "right" else -1.0
        up, right = d * (x - x[0]), -d * (y - y[0])
        if np.sign(R.FIELD_CENTER_Y - y[0]) != np.sign(-d):  # middle of the field on the receiver's left: mirror
            right = -right
        ax.plot(right, up, color=INK2, lw=1, alpha=0.55)
        if key in kept_by:
            for _, c in kept_by[key].iterrows():
                a = int(c.apex_frame)
                inside = c.break_side == "in"
                ax.plot(right[a], up[a], "o" if inside else "s", ms=7, mfc=SERIES[0] if inside else SERIES[1],
                        mec=SURFACE, mew=1.2, zorder=3)
    share = per_route.loc[rt, "with a break"]
    ax.set_title(f"{rt.title()} · break found on {share} of routes", loc="left")
    ax.set_aspect("equal", "datalim")
    ax.axvline(0, color=GRID, lw=1, zorder=0)
for ax in axes[:, 0]:
    ax.set_ylabel("downfield (yd)")
for ax in axes[1]:
    ax.set_xlabel("toward the middle of the field (yd)")
legend = [Line2D([], [], ls="", marker="o", ms=7, mfc=SERIES[0], mec=SURFACE, label="inside break"),
          Line2D([], [], ls="", marker="s", ms=7, mfc=SERIES[1], mec=SURFACE, label="outside break")]
fig.legend(handles=legend, loc="upper right", frameon=False, ncol=2, fontsize=9, labelcolor=INK)
fig.suptitle("Route breaks the combine detector finds in games: 12 random routes per route type, snap to 0.5 s "
             "after the throw.\nEvery path starts at (0, 0); downfield is up and the middle of the field is to the "
             "right.", x=0.01, ha="left", color=INK, fontsize=11)
fig.tight_layout(rect=(0, 0, 1, 0.95))
fig.savefig(FIGURES / "02_game_breaks.png", dpi=90)
plt.close(fig)
report.extend(["## Figure", "", "![Route breaks found in games](figures/02_game_breaks.png)", ""])

# %%
zc.to_parquet(FEATURES / "game_cuts.parquet", index=False)
routes.merge(sr[[*R.KEY, "ttt_bin", "expected_separation", "soe"]], on=R.KEY, how="left").to_parquet(
    FEATURES / "game_routes.parquet", index=False)
wr.to_parquet(FEATURES / "wr_analysis.parquet")
report[4:4] = ["## Checks", "", *checks, ""]
out = ROOT / "reports" / "02_game_features.md"
out.write_text("\n".join(report))
print(f"\n{len(checks)} checks passed; {len(wr)} WRs; wrote {out.relative_to(ROOT)}")
