# %% [markdown]
# # Phase 3 — pre-registered models
#
# Runs exactly the analysis plan pre-registered in PLAN.md ("Phase 3 analysis plan", commit 6d770a1,
# committed before any combine–game or outcome link was computed):
#
# - Test 1, link (1): does each combine cut trait carry into the same trait in games, beyond the baseline?
# - Test 2, link (2): on routes where a WR cuts better than their own average, are they more open (SOE)?
# - Test 3, headline: does each combine cut trait predict SOE beyond the baseline? Plus a leave-one-draft-
#   class-out check of baseline vs baseline + the three signals.
#
# Writes `reports/03_models.md` + `reports/figures/03_*.png`. Every `check(...)` is a hard assertion.
#
# Run: `python notebooks/03_models.py` (after `notebooks/02_game_features.py`)

# %%
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import matplotlib  # noqa: E402

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402
from matplotlib.lines import Line2D  # noqa: E402

from src import features as F  # noqa: E402
from src import models as M  # noqa: E402
from src.stats import detectable_r, split_half  # noqa: E402

FEATURES = ROOT / "data" / "features"
FIGURES = ROOT / "reports" / "figures"
FIGURES.mkdir(parents=True, exist_ok=True)
for f in ("wr_analysis.parquet", "game_cuts.parquet", "game_routes.parquet", "combine_cuts.parquet"):
    if not (FEATURES / f).exists():
        raise SystemExit(f"Missing {f}: run notebooks/01_combine_features.py and 02_game_features.py first.")

N_BOOT = 2000
MIN_ROUTES = 100
KEY = ["game_id", "play_id", "nfl_id"]
PRIMARY = ["entry_speed", "speed_retention", "peak_lat_accel"]
SECONDARY = ["peak_decel"]
SIGNALS = PRIMARY + SECONDARY
NAMES = {"entry_speed": "speed into the break", "speed_retention": "speed retention",
         "peak_lat_accel": "peak lateral acceleration", "peak_decel": "peak braking (secondary)"}

report: list[str] = ["# Phase 3 — pre-registered models", "",
                     "Generated by `notebooks/03_models.py`. Do not edit by hand.", ""]
checks: list[str] = []


def check(name: str, ok: bool, detail: str = "") -> None:
    checks.append(f"- [{'x' if ok else ' '}] {name}" + (f" — {detail}" if detail else ""))
    assert ok, f"{name}: {detail}"


def md_table(d: pd.DataFrame, index: bool = False) -> str:
    if index:
        d = d.reset_index()

    def fmt(v):
        if isinstance(v, str):
            return v.replace("|", "\\|")
        if pd.isna(v):
            return ""
        if isinstance(v, (int, np.integer)) or (isinstance(v, float) and v == int(v) and abs(v) >= 10):
            return f"{int(v):,}"
        return f"{round(float(v), 3) + 0.0:.3f}" if abs(v) < 0.1 else f"{round(float(v), 2) + 0.0:.2f}"

    rows = ["| " + " | ".join(map(str, d.columns)) + " |", "|" + "---|" * d.shape[1]]
    rows += ["| " + " | ".join(fmt(v) for v in r) + " |" for r in d.itertuples(index=False)]
    return "\n".join(rows)


def section(title: str, d: pd.DataFrame | None = None, note: str = "", index: bool = False) -> None:
    report.extend([f"## {title}", ""])
    if note:
        report.extend([note, ""])
    if d is not None:
        report.extend([md_table(d, index), ""])
    print(f"\n== {title}\n{'' if d is None else d.to_string()}")


def pfmt(p: float) -> str:
    return "< 0.001" if p < 0.001 else f"{p:.3f}"


def verdict(p_holm: float, p: float, yes: str) -> str:
    return yes if p_holm < 0.05 else ("suggestive" if p < 0.05 else "no evidence")


def ci_str(lo: float, hi: float, digits: int = 2) -> str:
    return f"[{lo:+.{digits}f}, {hi:+.{digits}f}]"


# Chart styling: same reference palette (dataviz skill) and recessive axes as Phases 1–2.
SERIES = ["#2a78d6", "#eb6834", "#1baf7a"]
SURFACE, INK, INK2, GRID = "#fcfcfb", "#0b0b0b", "#52514e", "#e4e3df"
plt.rcParams.update({
    "figure.facecolor": SURFACE, "axes.facecolor": SURFACE, "savefig.facecolor": SURFACE,
    "axes.edgecolor": GRID, "axes.labelcolor": INK2, "xtick.color": INK2, "ytick.color": INK2,
    "axes.titlecolor": INK, "axes.titlesize": 10, "axes.labelsize": 9, "xtick.labelsize": 8, "ytick.labelsize": 9,
    "axes.spines.top": False, "axes.spines.right": False, "axes.spines.left": False, "axes.grid": True,
    "grid.color": GRID, "grid.linewidth": 0.6, "lines.linewidth": 2, "font.size": 9,
})

# %% [markdown]
# ## 0. Sample and baseline

# %%
wr = pd.read_parquet(FEATURES / "wr_analysis.parquet")
q = wr[wr.routes.fillna(0) >= MIN_ROUTES].copy()
check(f"62 qualified WRs (≥ {MIN_ROUTES} regular-season routes), as pre-registered", len(q) == 62, f"{len(q)}")
need = [f"pos_{m}" for m in SIGNALS] + [f"game_{m}" for m in SIGNALS] + ["soe"]
check("every qualified WR has all combine and game signals and SOE", bool(q[need].notna().all().all()))
B, B_medians = M.baseline_matrix(q)
miss = wr.loc[q.index, ["draft_overall_pick", "forty", "ten_yd_split", "vertical", "broad_jump"]].isna().sum()
report.extend([
    "## Method", "",
    "Exactly the plan pre-registered in PLAN.md (\"Phase 3 analysis plan\", commit `6d770a1`), which was committed "
    "before any combine–game or outcome link was computed. In short:",
    "",
    f"- **Sample:** the {len(q)} qualified WRs (≥ {MIN_ROUTES} regular-season routes); classes "
    + ", ".join(f"{int(k)}: {v}" for k, v in q.groupby("draft_year").size().items()) + ".",
    "- **Baseline (B):** log(draft pick) with UDFAs at pick 260 plus a UDFA flag, 40, 10-yd split, vertical, broad "
    f"jump, height, weight. Missing tests filled with the sample median ({miss['forty']} missing 40s, "
    f"{miss['vertical']} verticals, {miss['broad_jump']} broad jumps; {int(miss['draft_overall_pick'])} UDFAs).",
    "- **Test 1:** OLS of the game trait on B + the combine trait; HC3 p, player-bootstrap CI.",
    "- **Test 2:** route-level SOE on the route's mean break score split into within-player and player-mean parts; "
    "player-clustered p, player-cluster bootstrap CI.",
    "- **Test 3:** OLS of player SOE on B + the combine trait; HC3 p, bootstrap CI. Out of sample: ridge, leave one "
    "draft class out, B vs B + the three primary signals.",
    f"- Holm correction within each test's 3 primary signals; {N_BOOT:,} bootstrap resamples; braking and the "
    "other secondary analyses are not corrected.",
    "",
])

# %% [markdown]
# ## 1. Reliabilities (from Phases 1–2), for the disattenuated r and the power column

# %%
ccuts = pd.read_parquet(FEATURES / "combine_cuts.parquet")
crel = F.split_half_reliability(ccuts[ccuts.drill_type == "SKILL_DRILLS_WR"], n_iter=200,
                                metrics=tuple(SIGNALS)).set_index("feature").reliability
gcuts = pd.read_parquet(FEATURES / "game_cuts.parquet")
grel = split_half(gcuts, [f"{m}_z" for m in SIGNALS], players=q.index).set_index("feature").reliability
grel.index = grel.index.str.removesuffix("_z")
check("reliabilities match Phase 2 (game speed into the break 0.77)", abs(grel["entry_speed"] - 0.77) < 0.01,
      f"{grel['entry_speed']:.3f}")


def player_test(y: pd.Series, m: str, standardize_y: bool, sample: pd.DataFrame | None = None) -> dict:
    """OLS of y on the baseline + combine trait m (all standardized) over `sample` (default: the 62 qualified
    WRs); HC3 p and a player-bootstrap CI for the trait's coefficient."""
    sample = q if sample is None else sample
    Bs = B if sample is q else M.baseline_matrix(sample)[0]
    X = M.zscore(pd.concat([Bs, sample[f"pos_{m}"]], axis=1))
    yy = (y - y.mean()) / y.std(ddof=0) if standardize_y else y
    fit = M.ols(yy.to_numpy(), X.to_numpy())
    Xraw, yraw = pd.concat([Bs, sample[f"pos_{m}"]], axis=1).to_numpy(), y.to_numpy()

    def stat(idx):
        Xi = Xraw[idx]
        sd = Xi.std(axis=0)
        Xi = (Xi - Xi.mean(axis=0)) / np.where(sd > 0, sd, 1.0)
        yi = yraw[idx]
        yi = (yi - yi.mean()) / yi.std() if standardize_y else yi
        X1 = np.column_stack([np.ones(len(idx)), Xi])
        return np.linalg.lstsq(X1, yi, rcond=None)[0][-1]

    draws = M.bootstrap(stat, np.arange(len(sample)), N_BOOT, seed=0)
    lo, hi = M.percentile_ci(draws)
    return {"coef": fit["coef"][-1], "lo": lo, "hi": hi, "p": fit["p"][-1], "partial_r": fit["partial_r"][-1],
            "boot_fail": np.isnan(draws).mean()}


# %% [markdown]
# ## 2. Test 1 — link (1): combine trait → same trait in games

# %%
t1 = []
for m in SIGNALS:
    r = player_test(q[f"game_{m}"], m, standardize_y=True)
    raw = q[f"pos_{m}"].corr(q[f"game_{m}"])
    t1.append({"m": m, **r, "raw_r": raw, "disattenuated_r": raw / np.sqrt(crel[m] * grel[m])})
t1 = pd.DataFrame(t1).set_index("m")
t1["p_holm"] = np.nan
t1.loc[PRIMARY, "p_holm"] = M.holm(t1.loc[PRIMARY, "p"])
check("bootstrap fits succeed (≥ 99%)", (t1.boot_fail < 0.01).all())
det_r = detectable_r(len(q))
tab1 = pd.DataFrame({
    "combine reliability": crel[SIGNALS].values, "game reliability": grel[SIGNALS].values,
    "raw r": t1.raw_r.values, "disattenuated r": t1.disattenuated_r.values,
    "beyond baseline: β (SD per SD)": t1.coef.values,
    "95% CI": [ci_str(a, b) for a, b in zip(t1.lo, t1.hi)],
    "partial r": t1.partial_r.values,
    "p": [pfmt(v) for v in t1.p], "Holm p": ["" if pd.isna(v) else pfmt(v) for v in t1.p_holm],
    "verdict": [verdict(ph, p, "carries over") if m in PRIMARY else ("p < 0.05" if p < 0.05 else "no evidence")
                for m, ph, p in zip(t1.index, t1.p_holm, t1.p)],
}, index=[NAMES[m] for m in SIGNALS]).rename_axis("signal")
section("Test 1: which combine traits carry into games (translation table)", tab1, index=True,
        note=f"Game trait regressed on the baseline plus the combine trait, all standardized, {len(q)} WRs. β is the "
             "SD change in the game trait per SD of the combine trait with draft pick and athletic testing held "
             "fixed. Disattenuated r = raw r / √(combine reliability × game reliability): what the raw r would be "
             f"without measurement noise (descriptive, not tested). With {len(q)} WRs a test needs an observed |r| ≥ "
             f"{det_r:.2f} for 80% power.")

# %% [markdown]
# ## 3. Test 2 — link (2): break score → separation over expected, within player

# %%
routes = pd.read_parquet(FEATURES / "game_routes.parquet")
routes = routes[routes.nfl_id.isin(q.index) & routes.soe.notna()]
qcuts = gcuts[gcuts.nfl_id.isin(q.index)]
CLASS = q.draft_year


def route_scores(cuts: pd.DataFrame) -> pd.DataFrame:
    """One row per route with SOE and the mean break score per signal over the given breaks."""
    x = cuts.groupby(KEY)[[f"{m}_z" for m in SIGNALS]].mean().reset_index()
    return routes[[*KEY, "soe"]].merge(x, on=KEY)


def within_test(d: pd.DataFrame, cols: list[str], boot: bool = True) -> dict:
    """SOE on within-player and player-mean parts of route break scores (each in route-level SD units).

    Returns the within-player coefficient of the first column, with clustered p and a cluster-bootstrap CI.
    """
    d = d.copy()
    X = []
    for c in cols:
        x = d[c] / d[c].std()
        xbar = x.groupby(d.nfl_id).transform("mean")
        d[f"{c}_w"], d[f"{c}_b"] = x - xbar, xbar
        X += [f"{c}_w", f"{c}_b"]
    fit = M.ols(d.soe.to_numpy(), d[X].to_numpy(), cluster=d.nfl_id.to_numpy())
    out = {"b_w": fit["coef"][1], "p": fit["p"][1], "b_b": fit["coef"][2], "p_b": fit["p"][2],
           "routes": len(d), "WRs": d.nfl_id.nunique()}
    if boot:
        players = d.nfl_id.unique()
        rows = {p: np.flatnonzero(d.nfl_id.to_numpy() == p) for p in players}
        Xa = np.column_stack([np.ones(len(d)), d[X].to_numpy()])
        ya = d.soe.to_numpy()

        def stat(idx):
            r = np.concatenate([rows[players[i]] for i in idx])
            return np.linalg.lstsq(Xa[r], ya[r], rcond=None)[0][1]

        draws = M.bootstrap(stat, players, N_BOOT, seed=0)
        out["lo"], out["hi"] = M.percentile_ci(draws)
    return out


pre = route_scores(qcuts[qcuts.t_after_throw <= 1e-9])
check("route-level sample is the pre-registered ~8,400 routes", 8000 <= len(pre) <= 8800, f"{len(pre):,} routes")
t2 = pd.DataFrame({m: within_test(pre, [f"{m}_z"]) for m in SIGNALS}).T
t2["p_holm"] = np.nan
t2.loc[PRIMARY, "p_holm"] = M.holm(t2.loc[PRIMARY, "p"].astype(float))
tab2 = pd.DataFrame({
    "within-player effect (yd SOE per SD)": t2.b_w.astype(float).values,
    "95% CI": [ci_str(a, b, 3) for a, b in zip(t2.lo, t2.hi)],
    "p": [pfmt(v) for v in t2.p], "Holm p": ["" if pd.isna(v) else pfmt(v) for v in t2.p_holm],
    "verdict": [verdict(ph, p, "matters") if m in PRIMARY else ("p < 0.05" if p < 0.05 else "no evidence")
                for m, ph, p in zip(t2.index, t2.p_holm, t2.p)],
    "player-mean effect (yd per SD)": t2.b_b.astype(float).values,
    "player-mean p": [pfmt(v) for v in t2.p_b],
}, index=[NAMES[m] for m in SIGNALS]).rename_axis("signal")
section("Test 2: does the mechanic matter on the field?", tab2, index=True,
        note=f"{len(pre):,} routes from {pre.nfl_id.nunique()} WRs with a separation value and at least one break "
             "at or before the throw. Within-player effect: yd of separation over expected per 1 SD of the route's "
             "break score, comparing a WR's routes with each other, so the WR's role, QB and scheme cancel out. "
             "Player-mean effect: the same between WRs (confounded by those, reported only). "
             f"SOE has an SD of {pre.soe.std():.2f} yd per route.")

# %% [markdown]
# ## 4. Test 3 — headline: combine trait → SOE beyond the baseline

# %%
t3 = pd.DataFrame({m: player_test(q.soe, m, standardize_y=False) for m in SIGNALS}).T
t3["p_holm"] = np.nan
t3.loc[PRIMARY, "p_holm"] = M.holm(t3.loc[PRIMARY, "p"].astype(float))
tab3 = pd.DataFrame({
    "yd SOE per SD, beyond baseline": t3.coef.astype(float).values,
    "95% CI": [ci_str(a, b, 3) for a, b in zip(t3.lo, t3.hi)],
    "partial r": t3.partial_r.astype(float).values,
    "p": [pfmt(v) for v in t3.p], "Holm p": ["" if pd.isna(v) else pfmt(v) for v in t3.p_holm],
    "verdict": [verdict(ph, p, "predicts") if m in PRIMARY else ("p < 0.05" if p < 0.05 else "no evidence")
                for m, ph, p in zip(t3.index, t3.p_holm, t3.p)],
}, index=[NAMES[m] for m in SIGNALS]).rename_axis("signal")
section("Test 3: does the combine trait predict separation beyond the baseline?", tab3, index=True,
        note=f"Player SOE (yd, mean over each WR's routes; SD across WRs {q.soe.std():.2f} yd) regressed on the "
             "baseline plus the combine trait (standardized).")


def build(cols):
    def _build(train, test):
        Btr, med = M.baseline_matrix(train)
        Bte, _ = M.baseline_matrix(test, med)
        Xtr = pd.concat([Btr, train[cols]], axis=1)
        Xte = pd.concat([Bte, test[cols]], axis=1)
        return M.zscore(Xtr), M.zscore(Xte, ref=Xtr)
    return _build


lo_rows = []
for label, cols in [("baseline", []), ("baseline + 3 combine cut signals", [f"pos_{m}" for m in PRIMARY])]:
    pred = M.leave_one_group_out(q, "soe", build(cols), "draft_year")
    row = {"model": label, "pooled out-of-sample R²": M.oos_r2(q.soe, pred)}
    for c in sorted(q.draft_year.unique()):
        k = q.draft_year == c
        row[f"MSE, {int(c)} held out"] = float(np.mean((q.soe[k] - pred[k]) ** 2))
    lo_rows.append(row)
lodo = pd.DataFrame(lo_rows).set_index("model")
check("each draft class is held out once", lodo.filter(like="held out").shape[1] == 3)
gain = lodo.iloc[1, 0] - lodo.iloc[0, 0]
section("Test 3, out of sample: leave one draft class out", lodo, index=True,
        note="Ridge regression (penalty chosen by generalized cross-validation inside the two training classes), "
             f"predicting the held-out class's player SOE. Gain from adding the three signals: {gain:+.3f} R². "
             "Negative R² means the model predicts held-out WRs worse than their class-pooled mean would.")

base_fit = M.ols(q.soe.to_numpy(), M.zscore(B).to_numpy())
base_tab = pd.DataFrame({"yd SOE per SD": base_fit["coef"][1:], "p": [pfmt(v) for v in base_fit["p"][1:]]},
                        index=B.columns).rename_axis("baseline term")
section("Exploratory (not pre-registered): what the baseline picks up in SOE", base_tab, index=True,
        note="Added after the pre-registered tests ran, to explain the baseline's out-of-sample R². Weight carries "
             "it: heavier WRs are less open. SOE adjusts for route, coverage and time to throw but not alignment, so "
             "this is probably role (bigger outside receivers vs lighter slot receivers) rather than a cutting effect; "
             "that explanation is not tested here.")

# %% [markdown]
# ## 5. Secondary analyses (pre-registered, not corrected)

# %%
sec = []
for outcome, label in [("target_rate", "target rate"), ("yprr", "yards per route run")]:
    for m in PRIMARY:
        r = player_test(q[outcome], m, standardize_y=True)
        sec.append({"analysis": f"Test 3 on {label} (SD per SD)", "signal": NAMES[m], "estimate": r["coef"],
                    "95% CI": ci_str(r["lo"], r["hi"]), "p": pfmt(r["p"])})
qr_mask = wr.rookie_routes.fillna(0) >= MIN_ROUTES
qr = wr[qr_mask & wr.rookie_soe.notna()]
for m in PRIMARY:
    r = player_test(qr.rookie_soe, m, standardize_y=False, sample=qr)
    sec.append({"analysis": f"Test 3 on rookie-season SOE (yd per SD; {len(qr)} WRs)", "signal": NAMES[m],
                "estimate": r["coef"], "95% CI": ci_str(r["lo"], r["hi"], 3), "p": pfmt(r["p"])})
allk = route_scores(qcuts)
for m in PRIMARY:
    r = within_test(allk, [f"{m}_z"])
    sec.append({"analysis": f"Test 2 with all kept breaks ({len(allk):,} routes)", "signal": NAMES[m],
                "estimate": r["b_w"], "95% CI": ci_str(r["lo"], r["hi"], 3), "p": pfmt(r["p"])})
for c in sorted(q.draft_year.unique()):
    d = pre[pre.nfl_id.map(CLASS) == c]
    for m in PRIMARY:
        r = within_test(d, [f"{m}_z"], boot=False)
        sec.append({"analysis": f"Test 2, {int(c)} class only ({r['WRs']} WRs)", "signal": NAMES[m],
                    "estimate": r["b_w"], "95% CI": "", "p": pfmt(r["p"])})
sec = pd.DataFrame(sec)
section("Secondary analyses", sec,
        note="Pre-registered as secondary: reported for context, no multiple-testing correction, no verdicts.")

# %% [markdown]
# ## 6. Figure: the three tests side by side

# %%
fig, axes = plt.subplots(1, 3, figsize=(13, 3.6), sharey=True)
panels = [
    (t1, "coef", "Test 1 · combine → game trait\nβ beyond baseline (SD per SD)", "p_holm"),
    (t2, "b_w", "Test 2 · break score → separation\nwithin-player effect (yd SOE per SD)", "p_holm"),
    (t3, "coef", "Test 3 · combine trait → separation\nbeyond baseline (yd SOE per SD)", "p_holm"),
]
ypos = np.arange(len(SIGNALS))[::-1]
for ax, (t, col, title, ph) in zip(axes, panels):
    for y, m in zip(ypos, SIGNALS):
        est, lo, hi = float(t.loc[m, col]), float(t.loc[m, "lo"]), float(t.loc[m, "hi"])
        color = SERIES[0] if m in PRIMARY else INK2
        sig = m in PRIMARY and float(t.loc[m, ph]) < 0.05
        ax.plot([lo, hi], [y, y], color=color, lw=2, solid_capstyle="round")
        ax.plot(est, y, "o", ms=8, mfc=color if sig else SURFACE, mec=color, mew=2, zorder=3)
    ax.axvline(0, color=INK2, lw=1, zorder=0)
    ax.set_title(title, loc="left")
    ax.grid(axis="y", visible=False)
    ax.tick_params(axis="y", length=0)
axes[0].set_yticks(ypos, [NAMES[m] for m in SIGNALS])
legend = [Line2D([], [], ls="", marker="o", ms=8, mfc=SERIES[0], mec=SERIES[0], mew=2,
                 label="primary signal, Holm p < 0.05"),
          Line2D([], [], ls="", marker="o", ms=8, mfc=SURFACE, mec=SERIES[0], mew=2,
                 label="primary signal, not significant after Holm"),
          Line2D([], [], ls="", marker="o", ms=8, mfc=SURFACE, mec=INK2, mew=2, label="secondary (not corrected)")]
fig.legend(handles=legend, loc="lower center", ncol=3, frameon=False, fontsize=8, labelcolor=INK)
fig.suptitle("Estimates with 95% bootstrap intervals, 62 qualified WRs", x=0.01, ha="left", color=INK, fontsize=11)
fig.tight_layout(rect=(0, 0.08, 1, 0.95))
fig.savefig(FIGURES / "03_tests.png", dpi=90)
plt.close(fig)
report.extend(["## Figure", "", "![The three pre-registered tests](figures/03_tests.png)", ""])

# %%
report[4:4] = ["## Checks", "", *checks, ""]
out = ROOT / "reports" / "03_models.md"
out.write_text("\n".join(report))
print(f"\n{len(checks)} checks passed; wrote {out.relative_to(ROOT)}")
