"""Markdown report helpers shared by the notebooks: hard checks, sections and tables."""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd


def md_table(d: pd.DataFrame, index: bool = False) -> str:
    if index:
        d = d.reset_index()

    def fmt(v, col):
        if isinstance(v, str):
            return v.replace("|", "\\|")
        if pd.isna(v):
            return ""
        if isinstance(v, (bool, np.bool_)):
            return "yes" if v else "no"
        if col == "season" or col.endswith("year"):
            return str(int(v))  # 2023, not 2,023
        if isinstance(v, (int, np.integer)) or (isinstance(v, float) and v == int(v) and abs(v) >= 10):
            return f"{int(v):,}"
        return f"{v:.2f}"

    cols = [str(c) for c in d.columns]
    rows = ["| " + " | ".join(c.replace("|", "\\|") for c in cols) + " |", "|" + "---|" * len(cols)]
    rows += ["| " + " | ".join(fmt(v, c) for v, c in zip(r, cols)) + " |" for r in d.itertuples(index=False)]
    return "\n".join(rows)


class Report:
    """Collects checks and sections; `check` is a hard assertion that is also listed in the report."""

    def __init__(self, title: str, source: str):
        self.lines = [f"# {title}", "", f"Generated by `{source}`. Do not edit by hand.", ""]
        self.checks: list[str] = []

    def check(self, name: str, ok: bool, detail: str = "") -> None:
        self.checks.append(f"- [{'x' if ok else ' '}] {name}" + (f" — {detail}" if detail else ""))
        assert ok, f"{name}: {detail}"

    def text(self, *lines: str) -> None:
        self.lines.extend([*lines, ""])

    def section(self, title: str, d: pd.DataFrame | None = None, note: str = "", index: bool = False) -> None:
        self.lines.extend([f"## {title}", ""])
        if note:
            self.lines.extend([note, ""])
        if d is not None:
            self.lines.extend([md_table(d, index), ""])
        print(f"\n== {title}\n{'' if d is None else d.to_string()}")

    def write(self, path: Path) -> None:
        lines = self.lines[:4] + ["## Checks", "", *self.checks, ""] + self.lines[4:]
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("\n".join(lines))
